FROM openjdk:7u131-jdk
MAINTAINER Perseids Project <perseids@tufts.edu>

RUN apt-get update && apt-get install -y curl expect cadaver

WORKDIR /tmp
RUN curl -LO http://downloads.sourceforge.net/exist/Stable/2.2/eXist-db-setup-2.2.jar
ADD exist-setup.cmd /tmp/exist-setup.cmd
RUN expect -f exist-setup.cmd
RUN rm eXist-db-setup-2.2.jar exist-setup.cmd

EXPOSE 8080 8443
ENV EXIST_HOME /opt/exist
WORKDIR /opt/exist
ADD alpheios /tmp/alpheios
ADD cts /tmp/cts
ADD exist-startup.sh /tmp/exist-startup.sh
RUN /tmp/exist-startup.sh

CMD tools/wrapper/bin/exist.sh console

